In [ ]:
#get rid of hashtags below and run the code to access datasets
#import kagglehub

# Download latest version
#path_1 = kagglehub.dataset_download("bwandowando/spotify-songs-with-attributes-and-lyrics")

#path_2 = kagglehub.dataset_download("thedevastator/spotify-tracks-genre-dataset")

#print("Path to dataset files:", path_1)

#print("Path to dataset files:", path_2)

In [1]:
#Import statements
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# 1. Data Cleaning

In [3]:
# Load the dataset
df_songs_with_attributes = pd.read_csv("Datasets/songs_with_attributes_and_lyrics.csv")
print(f"Dataset shape: {df_songs_with_attributes.shape}")
df_songs_with_attributes.head()

Dataset shape: (955320, 17)

,id,name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,lyrics
0,0Prct5TDjAnEgIqbxcldY9,!,UNDEN!ABLE,HELLYEAH,0.415,0.6050,7,-11.157,1,0.0575,0.00116,0.838000,0.4710,0.193,100.059,79500.0,"He said he came from Jamaica,\n he owned a cou..."
1,2ASl4wirkeYm3OWZxXKYuq,!!,NaN,Yxngxr1,0.788,0.6480,7,-9.135,0,0.3150,0.90000,0.000000,0.1760,0.287,79.998,114000.0,"Fucked a bitch, now she running with my kids\n..."
2,69lcggVPmOr9cvPx9kLiiN,!!! - Interlude,Where I Belong EP,Glowie,0.000,0.0354,7,-20.151,0,0.0000,0.90800,0.000000,0.4790,0.000,0.000,11413.0,"Oh, my God, I'm going crazy\n"
3,4U7dlZjg1s9pjdppqZy0fm,!!De Repente!!,Un Palo Al Agua (20 Grandes Canciones),Rosendo,0.657,0.8820,5,-6.340,1,0.0385,0.00740,0.000013,0.0474,0.939,123.588,198173.0,Continuamente se extraña la gente si no puede ...
4,4v1IBp3Y3rpkWmWzIlkYju,!!De Repente!!,Fuera De Lugar,Rosendo,0.659,0.8930,5,-8.531,1,0.0411,0.09220,0.000019,0.0534,0.951,123.600,199827.0,Continuamente se extraña la gente si no puede ...

In [4]:
# Load the dataset
df_train = pd.read_csv("Datasets/train.csv")
print(f"Dataset shape: {df_train.shape}")
df_train.head()

Dataset shape: (114000, 21)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [7]:
genres = sorted(df_train['track_genre'].unique())

In [25]:
#keep only the columns we need from df_train
df_genres = df_train[["track_id", "track_genre"]]
#rename column
df_genres.rename(columns={'track_id': 'id'}, inplace=True)
df_genres.head()

/var/folders/vs/5yy_kg0d60d2y5l0k_5jk53c0000gn/T/ipykernel_97711/2565581548.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_genres.rename(columns={'track_id': 'id'}, inplace=True)

                       id track_genre
0  5SuOikwiRyPMVoIQDJUgSV    acoustic
1  4qPNDBW1i3p13qLCt0Ki3A    acoustic
2  1iJBSr7s7jYXzM8EGcbK5b    acoustic
3  6lfxq3CG4xtTiEg7opyCyx    acoustic
4  5vjLSffimiIP26QG5WcN2K    acoustic

In [26]:
#do the same for df_songs_with_attributes
df_lyrics = df_songs_with_attributes[["id", "artists", "lyrics"]]
df_lyrics.head()

,id,artists,lyrics
0,0Prct5TDjAnEgIqbxcldY9,HELLYEAH,"He said he came from Jamaica,\n he owned a cou..."
1,2ASl4wirkeYm3OWZxXKYuq,Yxngxr1,"Fucked a bitch, now she running with my kids\n..."
2,69lcggVPmOr9cvPx9kLiiN,Glowie,"Oh, my God, I'm going crazy\n"
3,4U7dlZjg1s9pjdppqZy0fm,Rosendo,Continuamente se extraña la gente si no puede ...
4,4v1IBp3Y3rpkWmWzIlkYju,Rosendo,Continuamente se extraña la gente si no puede ...

In [27]:
# Merging df_lyrics and df_genres

master_df = df_lyrics.merge(df_genres, on='id', how='inner')

master_df.info()
print(master_df.shape)
print(master_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80274 entries, 0 to 80273
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           80274 non-null  object
 1   artists      80274 non-null  object
 2   lyrics       80274 non-null  object
 3   track_genre  80274 non-null  object
dtypes: object(4)
memory usage: 2.4+ MB
(80274, 4)
                       id            artists  \
0  0fROT4kK5oTm8xO8PX6EJF              Rilès
1  1hH0t381PIXmUVWyG1Vj3p       Brian Hyland
2  1B45DvGMoFWdbAEUH2qliG  Little Apple Band
3  73lXf5if6MWVWnsgXhK8bd  Little Apple Band
4  5Zx0Rrkn5RFBMD2PRxX3mI     Dillinger Four

                                              lyrics track_genre
0  It's been a while, shit I missed the rehab, ps...      french
1  A You're adorable\n B You're so beautiful\n C ...  rockabilly
2  C is for cookie, that's good enough for me\n C...        kids
3  C is for cookie, that's good enough for me\n C...        kids
4  These obvious manipulations\n Predicated on th...   power-pop

In [ ]:
! pip install langdetect

In [29]:
# based on the results, we decided to keep lyrics that have equal or more than 100 words
master_df = master_df[master_df['word_count'] >= 100]

# want to make sure that the lyrics are in english
from langdetect import detect, LangDetectException

def detect_language(text):
    try:
        return detect(text)
    except LangDetectException:
        return 'unknown'

master_df['language'] = master_df['lyrics'].apply(detect_language)
master_df = master_df[master_df['language'] == 'en']
master_df = master_df.drop(columns=['language', 'word_count'])

print(f"Final rows: {len(master_df)}")

Final rows: 43482

In [30]:
# Make sure everything looks clean
print(master_df.info())
print(master_df['track_genre'].value_counts())
print(f"Unique genres: {master_df['track_genre'].nunique()}")

<class 'pandas.core.frame.DataFrame'>
Index: 43482 entries, 0 to 80238
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           43482 non-null  object
 1   artists      43482 non-null  object
 2   lyrics       43482 non-null  object
 3   track_genre  43482 non-null  object
dtypes: object(4)
memory usage: 1.7+ MB
None
track_genre
dance        930
house        903
metalcore    902
soul         898
grunge       892
            ...
mpb            6
salsa          4
sleep          2
forro          1
tango          1
Name: count, Length: 111, dtype: int64
Unique genres: 111

In [31]:
master_df.head()

,id,artists,lyrics,track_genre
0,0fROT4kK5oTm8xO8PX6EJF,Rilès,"It's been a while, shit I missed the rehab, ps...",french
1,1hH0t381PIXmUVWyG1Vj3p,Brian Hyland,A You're adorable\n B You're so beautiful\n C ...,rockabilly
2,1B45DvGMoFWdbAEUH2qliG,Little Apple Band,"C is for cookie, that's good enough for me\n C...",kids
3,73lXf5if6MWVWnsgXhK8bd,Little Apple Band,"C is for cookie, that's good enough for me\n C...",kids
4,5Zx0Rrkn5RFBMD2PRxX3mI,Dillinger Four,These obvious manipulations\n Predicated on th...,power-pop

In [32]:
# Load the dataset
df_parent_genre = pd.read_csv("Datasets/genre_parent_mapping.csv")
print(f"Dataset shape: {df_parent_genre.shape}")
df_parent_genre.head()

Dataset shape: (115, 4)

,original_genre,parent_genre,included,notes
0,0,NaN,False,Header artifact from source CSV
1,acoustic,NaN,False,Production style not a musical genre
2,afrobeat,World/Regional,True,NaN
3,alt-rock,Rock,True,NaN
4,alternative,Rock,True,NaN

In [33]:
df_merged = master_df.merge(
    df_parent_genre,
    left_on="track_genre",
    right_on="original_genre",
    how="left"
)

In [36]:
#keep only rows that have included = True
print(df_merged["included"].dtype)
print(df_merged["included"].unique())

df_filtered = df_merged[df_merged["included"]].copy()

print(f"Final rows: {len(df_filtered)}")

bool
[False  True]
Final rows: 36036

In [37]:
#how many genres do we now have?
sorted(df_filtered['parent_genre'].unique())

['Asian Pop',
 'Classical',
 'Electronic',
 'Folk/Country',
 'Hip-Hop & R&B',
 'Jazz & Blues',
 'Latin',
 'Metal',
 'Pop',
 'Reggae/Caribbean',
 'Rock',
 'Soul/Funk',
 'World/Regional']

In [38]:
print(df_filtered.groupby('parent_genre').size().sort_values(ascending=False))
print(f"\nTotal: {len(df_filtered)}")

parent_genre
Electronic          9614
Rock                7890
Metal               3818
Folk/Country        3796
Pop                 2603
Soul/Funk           2410
Asian Pop           1483
Jazz & Blues        1362
World/Regional      1061
Reggae/Caribbean     834
Hip-Hop & R&B        627
Classical            349
Latin                189
dtype: int64

Total: 36036